flags: {}
nix:
  packages:
  - zlib
  enable: true
  pure: false
extra-package-dbs: []
packages:
- '.'
extra-deps:
- base-compat-0.9.1
- base-orphans-0.5.4
- bytestring-builder-0.10.8.1.0
- foldl-1.2.1
- generic-deriving-1.10.5
- pipes-4.2.0
- pipes-bytestring-2.1.3
- pipes-concurrency-2.0.6
- pipes-extras-1.0.4
- pipes-group-1.0.5
- pipes-parse-3.0.7
- pipes-safe-2.2.4
- pipes-text-0.0.2.4
- text-1.2.2.1
resolver: lts-5.9
